apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kerberos-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi   # adjust size depending on how much video you want to store

